-- inserts

Insert INTO Reinos (nome) values 
('Animalia'),
('Plantae'),
('Fungi'),
('Protista'),
('Archaea'),
('Bacteria');

INSERT INTO Filos (nome, reino_id) values 
('Chordata', 1),
('Magnoliophyta', 2),
('Basidiomycota', 3),
('Arthropoda', 1),
('Annelida', 1),
('Cnidaria', 1),
('Mollusca', 1),
('Bryophyta', 2),
('Pteridophyta', 2),
('Chytridiomycota', 3),
('Protozoa', 4),
('Chlorophyta', 4),
('Thaumarchaeota', 5),
('Cyanobacteria', 6),
('Actinobacteria', 6);


INSERT INTO Classes (nome, filo_id) VALUES 
('Mammalia', 1),
('Aves', 1),
('Magnoliopsida', 2),
('Agaricomycetes', 3),
('Osteichthyes', 1),
('Reptilia', 1),
('Amphibia',1),
('Insecta', 4),
('Oligochaeta', 5),
('Hirudinea', 5),
('Polychaeta', 5),
('Anthozoa', 6),
('Gastropoda', 7),
('Liliopsida', 2),
('Bryopsida', 8),
('Polypodiopsida', 9),
('Agaricomycetes', 3),
('Chytridiomycetes', 10),
('Amoebozoa', 11),
('Chlorophyeae', 12),
('Thaumarchaeota', 13),
('Nostocophycideae', 14),
('Actinobacteria', 15);


INSERT INTO Ordens (nome, classe_id) VALUES --Extenso a partir desse ponto
('Carnivora', 1),
('Primates', 1),
('Rodentia', 1),
('Passeriformes', 2),
('Accipitriformes', 2),
('Psittaciformes', 2),
('Rosales', 3),
('Fabales', 3),
('Asterales', 3),
('Agaricales', 4),
('Boletales', 4),
('Russulales', 4),
('Perciformes', 5),
('Cypriniformes', 5),
('Siluriformes', 5),
('Squamata', 6),
('Testudines', 6),
('Crocodylia', 6),
('Anura', 7),
('Caudata', 7),
('Gymnophiona', 7),
('Coleoptera', 8),
('Lepidoptera', 8),
('Diptera', 8),
('Lumbriculida', 9),
('Haplotaxida', 9),
('Moniligastrida', 9),
('Rhynchobdellida', 10),
('Arhynchobdellida', 10),
('Phyllodocida', 11),
('Capitellida', 11),
('Scleractinia', 12),
('Actiniaria', 12),
('Stylommatophora', 13),
('Neogastropoda', 13),
('Poales', 14),
('Asparagales', 14),
('Hypnales', 15),
('Bryales', 15),
('Polypodiales', 16),
('Salviniales', 16),
('Agaricales', 4),
('Boletales', 4),
('Chytridiales', 17),
('Spizellomycetales', 17),
('Tubulinea', 18),
('Discosea', 18),
('Chlorococcales', 19),
('Volvocales', 19),
('Nitrososphaerales', 20),
('Nostocales', 21),
('Stigonematales', 21),
('Actinomycetales', 22),
('Corynebacteriales', 22);

INSERT INTO familias (nome, ordem_id) VALUES 
('Felidae', 1),
('Canidae', 1),
('Hominidae', 2),
('Cebidae', 2),
('Atalidae', 2)
('Muridae', 3),
('Sciuridae', 3),
('Fringillidae', 4),
('Turdidae', 4),
('Accipitridae', 5),
('Pandionidae', 5),
('Psittacidae', 6),
('Cacatuidae', 6),
('Rosaceae', 7),
('Moraceae', 7),
('Fabaceae', 8),
('Polygalaceae', 8),
('Asteraceae', 9),
('Campanulaceae', 9),
('Agaricaceae', 10),
('Cortinariaceae', 10),
('Boletaceae', 11),
('Gomphidiaceae', 11),
('Russulaceae', 12),
('Hericiaceae', 12),
('Percidae', 13),
('Serranidae', 13),
('Cyprinidae', 14),
('Cobitidae', 14),
('Ictaluridae', 15),
('Pimelodidae', 15),
('Gekkonidae', 16),
('Iguanidae', 16),
('Testudinidae', 17),
('Emydidae', 17),
('Crocodylidae', 18),
('Alligatoridae', 18),
('Ranidae', 19),
('Bufonidae', 19),
('Salamandridae', 20),
('Ambystomatidae', 20),
('Caeciliidae', 21),
('Typhlonectidae', 21),
('Carabidae', 22),
('Cerambycidae', 22),
('Nymphalidae', 23),
('Papilionidae', 23),
('Culicidae', 24),
('Drosophilidae', 24),
('Lumbricidae', 25),
('Enchytraeidae', 25),
('Tubificidae', 26),
('Haplotaxidae', 26),
('Moniligastridae', 27),
('Almidae', 27),
('Glossiphoniidae', 28),
('Piscicolidae', 28),
('Hirudinidae', 29),
('Erpobdellidae', 29),
('Phyllodocidae', 30),
('Nereididae', 30),
('Capitellidae', 31),
('Opheliidae', 31),
('Acroporidae', 32),
('Faviidae', 32),
('Actiniidae', 33),
('Metridiidae', 33),
('Helicidae', 34),
('Achatinidae', 34),
('Muricidae', 35),
('Conidae', 35),
('Poaceae', 36),
('Cyperaceae', 36),
('Orchidaceae', 37),
('Asparagaceae', 37),
('Hypnaceae', 38),
('Brachytheciaceae', 38),
('Bryaceae', 39),
('Mniaceae', 39),
('Polypodiaceae', 40),
('Dryopteridaceae', 40),
('Salviniaceae', 41),
('Marsileaceae', 41),
('Agaricaceae', 10),
('Cortinariaceae', 10),
('Chytridiaceae', 42),
('Rhizophlyctidaceae', 42),
('Spizellomycetaceae', 43),
('Olpidiaceae', 43),
('Amoebidae', 44),
('Hartmannellidae', 44),
('Vannellidae', 45),
('Acanthamoebidae', 45),
('Chlorococcaceae', 46),
('Oocystaceae', 46),
('Volvocaceae', 47),
('Goniaceae', 47),
('Nitrososphaeraceae', 48),
('Nostocaceae', 49),
('Rivulariaceae', 49),
('Stigonemataceae', 50),
('Fischerellaceae', 50),
('Streptomycetaceae', 51),
('Nocardiaceae', 51),
('Corynebacteriaceae', 52),
('Mycobacteriaceae', 52);

INSERT INTO generos (nome, familia_id) VALUES 
('Panthera', 1),
('Felis', 1),
('Canis', 2),
('Vulpes', 2),
('Homo', 3),
('Pan', 3),
('Cebus', 4),
('Saimiri', 4),
('Atelidae', 5),
('Alouatta', 5),
('Mus', 6),
('Rattus', 6),
('Sciurus', 7),
('Tamias', 7),
('Carduelis', 8),
('Spinus', 8),
('Turdus', 9),
('Catharus', 9),
('Aquila', 10),
('Buteo', 10),
('Pandion', 11),
('Amazona', 12),
('Eclectus', 12),
('Cacatua', 13),
('Calyptorhynchus', 13),
('Rosa', 14),
('Rubus', 14),
('Ficus', 15),
('Broussonetia', 15),
('Glycine', 16),
('Phaseolus', 16),
('Polygala', 17),
('Xerophyta', 17),
('Helianthus', 18),
('Aster', 18),
('Campanula', 19),
('Lobelia', 19),
('Agaricus', 20),
('Psilocybe', 20),
('Cortinarius', 21),
('Gymnopilus', 21),
('Boletus', 22),
('Suillus', 22),
('Gomphidius', 23),
('Gomphidius', 23),
('Russula', 24),
('Lactarius', 24),
('Hericium', 25),
('Lion’s Mane', 25),
('Perca', 26),
('Sander', 26),
('Serranus', 27),
('Epinephelus', 27),
('Cyprinus', 28),
('Danio', 28),
('Cobitis', 29),
('Misgurnus', 29),
('Ictalurus', 30),
('Ameiurus', 30),
('Pimelodus', 31),
('Brachyplatystoma', 31),
('Gekko', 32),
('Eublepharis', 32),
('Iguana', 33),
('Ctenosaura', 33),
('Testudo', 34),
('Geochelone', 34),
('Clemmys', 35),
('Graptemys', 35),
('Crocodylus', 36),
('Osteolaemus', 36),
('Alligator', 37),
('Paleosuchus', 37),
('Rana', 38),
('Lithobates', 38),
('Bufo', 39),
('Rhinella', 39),
('Salamandra', 40),
('Triturus', 40),
('Ambystoma', 41),
('Dicamptodon', 41),
('Caecilia', 42),
('Siphonops', 42),
('Typhlonectes', 43),
('Atretochoana', 43),
('Carabus', 44),
('Harpalus', 44),
('Cerambyx', 45),
('Dorcadion', 45),
('Danaus', 46),
('Vanessa', 46),
('Papilio', 47),
('Battus', 47),
('Anopheles', 48),
('Aedes', 48),
('Drosophila', 49),
('Zaprionus', 49),
('Lumbricus', 50),
('Eisenia', 50),
('Enchytraeus', 51),
('Fridericia', 51),
('Tubifex', 52),
('Limnodrilus', 52),
('Haplotaxis', 53),
('Haplotaxus', 53),
('Moniligaster', 54),
('Almidae', 54),
('Glossiphonia', 55),
('Helobdella', 55),
('Piscicola', 56),
('Pseudobiceros', 56),
('Hirudo', 57),
('Haemadipsa', 57),
('Erpobdella', 58),
('Tritomegas', 58),
('Phyllodoce', 59),
('Pseudophyllodoce', 59),
('Nereis', 60),
('Alkmaria', 60),
('Capitella', 61),
('Ophryotrocha', 61),
('Ophelia', 62),
('Ehlersia', 62),
('Acropora', 63),
('Montipora', 63),
('Favites', 64),
('Favia', 64),
('Actinia', 65),
('Metridium', 65),
('Metridium', 66),
('Haliplanella', 66),
('Helix', 67),
('Cornu', 67),
('Achatina', 68),
('Achatinella', 68),
('Murex', 69),
('Chicoreus', 69),
('Conus', 70),
('Turriconus', 70),
('Zea', 71),
('Oryza', 71),
('Cyperus', 72),
('Scleria', 72),
('Orchid', 73),
('Vanilla', 73),
('Asparagus', 74),
('Yucca', 74),
('Hypnum', 75),
('Plagiomnium', 75),
('Brachythecium', 76),
('Pseudotaxiphyllum', 76),
('Bryum', 77),
('Pottia', 77),
('Mnium', 78),
('Tortula', 78),
('Polypodium', 79),
('Phlebodium', 79),
('Dryopteris', 80),
('Thelypteris', 80),
('Salvinia', 81),
('Marsilea', 81),
('Marsilea', 82),
('Pilularia', 82),
('Chytridium', 83),
('Rhizophlyctis', 83),
('Rhizophlyctis', 84),
('Phaeosaccardin', 84),
('Spizellomyces', 85),
('Olpidiopsis', 85),
('Olpidiopsis', 86),
('Olpidiella', 86),
('Amoeba', 87),
('Entamoeba', 87),
('Hartmannella', 88),
('Hartmannella', 88),
('Vannella', 89),
('Vannella', 89),
('Acanthamoeba', 90),
('Naegleria', 90),
('Chlorococcum', 91),
('Oocystis', 91),
('Oocystis', 92),
('Chlorella', 92),
('Volvox', 93),
('Goniastrea', 93),
('Goniastrea', 94),
('Goniopora', 94),
('Nitrososphaera', 95),
('Nitrosotalea', 95),
('Nostoc', 96),
('Anabaena', 96),
('Rivularia', 97),
('Calothrix', 97),
('Stigonema', 98),
('Fischerella', 98),
('Fischerella', 99),
('Nostoc', 99),
('Streptomyces', 100),
('Kitasatospora', 100),
('Nocardia', 101),
('Rhodococcus', 101),
('Corynebacterium', 102),
('Arcanobacterium', 102),
('Mycobacterium', 103),
('Nocardia', 103);


INSERT INTO especies (nome_cientifico, nome_comum, descricao, status_conservacao, genero_id) VALUES 	
('Panthera tigris', 'Tigre', 'Um grande felino, de cor laranja conhecido por suas listras, quando você o vir é tarde demais', 'Não ameaçado', 1),
('Panthera leo', 'Leão', 'O rei da selva, se correr e pular em você, Teste de Resistência (FOR)', 'Vulnerável', 1),
('Felis catus', 'Gato Doméstico', 'Gato pequeno, conhecido como animal de estimação', 'Não ameaçado', 2),
('Felis silvestris', 'Gato Selvagem', 'Gato pequeno encontrado em áreas selvagens', 'Menos preocupante', 2),
('Canis lupus', 'Lobo Cinzento', 'Grande canídeo encontrado na América do Norte e Eurasia', 'Não ameaçado', 3),
('Vulpes vulpes', 'Raposa Vermelha', 'Canídeo pequeno encontrado em diversas regiões', 'Não ameaçado', 4),
('Homo sapiens', 'Humano', 'Espécie (se diz) dominante de hominídeos', 'Não ameaçado', 5),
('Pan troglodytes', 'Chimpanzé', 'Primata altamente inteligente e próximo ao ser humano', 'Ameaçado', 6),
('Cebus capucinus', 'Macaco-Prego', 'Macaco pequeno encontrado em florestas tropicais', 'Não ameaçado', 7),
('Saimiri sciureus', 'Saimiri', 'Pequeno macaco encontrado em áreas tropicais', 'Não ameaçado', 8),
('Alouatta seniculus', 'Bugio', 'Primata de grande porte conhecido pelo seu vocal e "rugido"', 'Não ameaçado', 9),
('Mus musculus', 'Camundongo', 'Pequeno roedor encontrado em todo o mundo', 'Não ameaçado', 10),
('Rattus norvegicus', 'Rato', 'Roedor encontrado em ambientes urbanos e rurais', 'Não ameaçado', 11),
('Sciurus carolinensis', 'Esquilo Cinza', 'Esquilo comum encontrado na América do Norte', 'Não ameaçado', 12),
('Tamias striatus', 'Esquilo de Faíscas', 'Esquilo pequeno encontrado na América do Norte', 'Não ameaçado', 13),
('Carduelis carduelis', 'Pintarroxo', 'Pequena ave com plumagem colorida encontrada na Europa', 'Não ameaçado', 14),
('Spinus tristis', 'Pintassilgo', 'Ave pequena encontrada na América do Norte', 'Não ameaçado', 15),
('Turdus merula', 'Sabiá laranjeira', 'Ave comum na Europa, conhecida pelo seu canto', 'Não ameaçado', 16),
('Catharus guttatus', 'Sabiá poca', 'Ave encontrada na América do Norte', 'Não ameaçado', 17),
('Aquila nipalensis', 'Águia Imperial', 'Grande águia encontrada na Ásia', 'Não ameaçado', 18),
('Buteo jamaicensis', 'Buzzard de Cauda Vermelha', 'Águia encontrada na América do Norte', 'Não ameaçado', 19),
('Pandion haliaetus', 'Águia Pesqueira', 'Águia especializada em pescar', 'Não ameaçado', 20),
('Amazona amazonica', 'Amazona', 'Papagaio encontrado na Amazônia', 'Não ameaçado', 21),
('Eclectus roratus', 'Eclectus', 'Papagaio colorido encontrado na Oceania', 'Não ameaçado', 22),
('Cacatua alba', 'Cacatua de bico amarelo', 'Papagaio encontrado na Indonésia', 'Não ameaçado', 23),
('Calyptorhynchus banksii', 'Cacatua de bico vermelho', 'Papagaio encontrado na Austrália', 'Não ameaçado', 24),
('Rosa rubiginosa', 'Rosa Selvagem', 'Planta conhecida por suas flores perfumadas e espinhos', 'Não ameaçado', 25),
('Ficus elastica', 'Figueira de borracha', 'Planta encontrada em florestas tropicais', 'Não ameaçado', 26),
('Glycine max', 'Soja', 'Planta leguminosa cultivada globalmente', 'Não ameaçado', 27),
('Phaseolus vulgaris', 'Feijão', 'Planta leguminosa cultivada em todo o mundo', 'Não ameaçado', 28),
('Helianthus annuus', 'Girassol', 'Planta conhecida por suas grandes flores amarelas', 'Não ameaçado', 29),
('Aster amellus', 'Aster', 'Planta com flores em formato de estrela', 'Não ameaçado', 30),
('Campanula rotundifolia', 'Campânula', 'Planta com flores em forma de sino', 'Não ameaçado', 31),
('Lobelia erinus', 'Lobélia', 'Planta com flores pequenas e intensamente coloridas', 'Não ameaçado', 32),
('Agaricus bisporus', 'Cogumelo Paris', 'Cogumelo comum encontrado em áreas úmidas', 'Não ameaçado', 33),
('Cortinarius violaceus', 'Cogumelo Violeta', 'Cogumelo encontrado em florestas', 'Não ameaçado', 34),
('Boletus edulis', 'Cogumelo Porcini', 'Cogumelo comestível encontrado em florestas', 'Não ameaçado', 35),
('Gomphidius glutinosus', 'Cogumelo Gomphidius', 'Cogumelo encontrado em áreas de floresta', 'Não ameaçado', 36),
('Russula emetica', 'Cogumelo Russula', 'Cogumelo encontrado em florestas', 'Não ameaçado', 37),
('Hericium erinaceus', 'Hérisson', 'Cogumelo com aparência de ouriço', 'Não ameaçado', 38),
('Perca fluviatilis', 'Lúcio', 'Peixe de água doce encontrado na Europa e Ásia', 'Não ameaçado', 39),
('Serranus cabrilla', 'Sargo', 'Peixe encontrado no Mediterrâneo', 'Não ameaçado', 40),
('Cyprinus carpio', 'Carpa', 'Peixe de água doce encontrado na Ásia e Europa', 'Não ameaçado', 41),
('Cobitis taenia', 'Locha', 'Peixe de água doce encontrado na Europa', 'Não ameaçado', 42),
('Ictalurus punctatus', 'Bagre de Canal', 'Peixe de água doce encontrado na América do Norte', 'Não ameaçado', 43),
('Pimelodus pictus', 'Bagre Pintado', 'Peixe encontrado na América do Sul', 'Não ameaçado', 44),
('Gekko gecko', 'Lagartixa', 'Lagartixa comum encontrada em áreas tropicais', 'Não ameaçado', 45),
('Iguana iguana', 'Iguana', 'Grande lagarto encontrado na América Central e do Sul', 'Não ameaçado', 46),
('Testudo graeca', 'Tartaruga Grega', 'Tartaruga terrestre encontrada na Europa e Ásia', 'Vulnerável', 47),
('Clemmys guttata', 'Tartaruga de Pinta', 'Tartaruga encontrada na América do Norte', 'Não ameaçado', 48),
('Crocodylus niloticus', 'Crocodilo do Nilo', 'Grande crocodilo encontrado na África', 'Não ameaçado', 49),
('Alligator mississippiensis', 'Jacaré Americano', 'Crocodilo encontrado no sudeste dos Estados Unidos', 'Não ameaçado', 50),
('Rana temporaria', 'Rã Comum', 'Rã encontrada na Europa', 'Não ameaçado', 51),
('Bufo bufo', 'Sapo Comum', 'Sapo encontrado na Europa', 'Não ameaçado', 52),
('Salamandra salamandra', 'Salamandra de fogo', 'Salamandra encontrada na Europa', 'Não ameaçado', 53),
('Ambystoma mexicanum', 'Axolote', 'Salamandra encontrada no México', 'Criticamente Ameaçado', 54),
('Caecilia tentaculata', 'Cecília', 'Anfíbio sem pernas encontrado na América Central', 'Não ameaçado', 55),
('Carabus auratus', 'Carabídeo Dourado', 'Inseto encontrado na Europa', 'Não ameaçado', 56),
('Cerambyx cerdo', 'Besouro Cerambícido', 'Besouro encontrado na Europa', 'Não ameaçado', 57),
('Danaus plexippus', 'Borboleta Monarca', 'Borboleta migratória encontrada na América do Norte', 'Não ameaçado', 58),
('Papilio machaon', 'Cavalo de frade', 'Borboleta encontrada na Europa e Ásia', 'Não ameaçado', 59),
('Anopheles gambiae', 'Mosquito da Malária', 'Mosquito encontrado na África', 'Não ameaçado', 60),
('Drosophila melanogaster', 'Mosca da fruta', 'Pequena mosca encontrada em todo o mundo', 'Não ameaçado', 61),
('Lumbricus terrestris', 'Minhoca', 'Minhoca encontrada em solo úmido', 'Não ameaçado', 62),
('Hirudo medicinalis', 'Sanguessuga Medicinal', 'Sanguessuga encontrada na Europa', 'Não ameaçado', 63),
('Nereis virens', 'Nereide', 'Poliqueta encontrada em áreas marinhas', 'Não ameaçado', 64),
('Acropora millepora', 'Coral Acropora', 'Coral encontrado em recifes tropicais', 'Ameaçado', 65),
('Favites pentagona', 'Coral Favite', 'Coral encontrado em recifes tropicais', 'Ameaçado', 66),
('Actinia equina', 'Anêmona do mar', 'Anêmona encontrada em áreas intertidais', 'Não ameaçado', 67),
('Achatina achatina', 'Caracol Gigante Africano', 'Caracol encontrado na África', 'Não ameaçado', 68),
('Conus textile', 'Caracol Cone', 'Caracol marinho encontrado no Indo-Pacífico', 'Não ameaçado', 69),
('Zea mays', 'Milho', 'Planta cultivada para alimentação em todo o mundo', 'Não ameaçado', 70),
('Vanilla planifolia', 'Baunilha', 'Planta cultivada por suas vagens aromáticas', 'Não ameaçado', 71),
('Asparagus officinalis', 'Aspargo', 'Planta cultivada como vegetal', 'Não ameaçado', 72),
('Bryum caespiticium', 'Musgo', 'Musgo encontrado em áreas sombreadas', 'Não ameaçado', 73),
('Polypodium vulgare', 'Polipódio', 'Samambaia encontrada em áreas úmidas', 'Não ameaçado', 74),
('Marsilea quadrifolia', 'Três Folhas', 'Planta aquática encontrada em áreas tropicais', 'Não ameaçado', 75),
('Rhizophlyctis rosea', 'Rhizophlyctis', 'Fungo aquático encontrado em água doce', 'Não ameaçado', 76),
('Amoeba proteus', 'Amoeba', 'Protista encontrado em água doce', 'Não ameaçado', 77),
('Entamoeba histolytica', 'Entamoeba', 'Protista parasita encontrado no trato intestinal', 'Não ameaçado', 78),
('Chlorococcum humicola', 'Chlorococcum', 'Algas verdes encontradas em solos úmidos', 'Não ameaçado', 79),
('Volvox aureus', 'Volvox', 'Algas formadoras de colônias encontradas em água doce', 'Não ameaçado', 80),
('Nostoc commune', 'Nostoc', 'Cianobactéria encontrada em ambientes úmidos', 'Não ameaçado', 81),
('Streptomyces griseus', 'Streptomyces', 'Bactéria produtora de antibióticos encontrada no solo', 'Não ameaçado', 82),
('Corynebacterium diphtheriae', 'Corynebactéria', 'Bactéria causadora de difteria encontrada em humanos', 'Não ameaçado', 83),
('Mycobacterium tuberculosis', 'Mycobactéria', 'Bactéria causadora da tuberculose', 'Não ameaçado', 84);


INSERT INTO doencas (nome, descricao, taxa_mortalidade) VALUES
('Raiva', 'Doença viral transmitida por mordidas de animais infectados, afeta o sistema nervoso central.', 100),
('Leptospirose', 'Infecção bacteriana transmitida pela urina de animais infectados, afeta vários órgãos.', 10),
('Tuberculose', 'Infecção bacteriana que afeta principalmente os pulmões, mas pode afetar outros órgãos.', 5),
('Parvovirose', 'Doença viral que afeta principalmente cães jovens, levando a diarreia grave.', 90),
('Distemper', 'Doença viral que afeta principalmente cães, com sintomas respiratórios e neurológicos.', 50),
('Newcastle', 'Doença viral que afeta aves, causando sintomas respiratórios e neurológicos.', 30),
('Psitacose', 'Infecção bacteriana que afeta papagaios e outros psitacídeos, podendo ser transmitida para humanos.', 15),
('Mareks', 'Doença viral que afeta galinhas, causando tumores e paralisia.', 50),
('Doença de Mouth Rot', 'Infecção bacteriana que afeta a boca dos répteis, causando úlceras e necrose.', 20),
('Cryptococose', 'Infecção fúngica que pode afetar répteis e outros animais, levando a problemas respiratórios e neurológicos.', 10),
('Ichthyophthirius', 'Doença parasitária causada por protozoários, que causa lesões na pele e nas brânquias.', 60),
('Vírus da Mancha Branca', 'Doença viral que afeta principalmente camarões, levando à mortalidade em larga escala.', 90),
('Míldio', 'Doença fúngica que afeta várias plantas, causando manchas e enfraquecimento.', 5),
('Ferrugem', 'Doença fúngica que afeta plantas cultivadas, levando à perda de folhas e redução na produção.', 20),
('Botrite', 'Doença fúngica que afeta frutas e flores, causando apodrecimento.', 30),
('Míldio', 'Doença fúngica que afeta plantas, causando manchas nas folhas.', 5),
('Esclerotinia', 'Doença fúngica que afeta plantas cultivadas, causando apodrecimento.', 20)
('Raiva', 'Doença viral transmitida pela mordida de animais infectados, que afeta o sistema nervoso central. É quase sempre fatal após o início dos sintomas.', 100),
('Leptospirose', 'Infecção bacteriana transmitida pela urina de animais infectados, que pode levar a febre, dor muscular e problemas renais. Se não tratada, pode ser fatal.', 10),
('Toxoplasmose', 'Infecção parasitária transmitida principalmente por gatos, que pode causar sintomas semelhantes aos da gripe e complicações graves em pessoas imunocomprometidas.', 2),
('Psitacose', 'Infecção bacteriana transmitida por aves como papagaios, que pode causar febre, tosse e pneumonia.', 5),
('Salmonelose', 'Infecção bacteriana que pode ser transmitida por aves contaminadas e causar sintomas gastrointestinais, como diarreia e febre.', 1),
('Salmonelose', 'Infecção bacteriana que pode ser transmitida por répteis, causando sintomas gastrointestinais como diarreia e febre.', 1),
('Histoplasmose', 'Infecção fúngica transmitida por esporos encontrados em excrementos de répteis, que pode causar sintomas respiratórios e sistêmicos.', 10),
('Anisakidose', 'Infecção parasitária transmitida pelo consumo de peixes crus ou mal cozidos, causando dor abdominal e náuseas.', 2),
('Cisticercose', 'Infecção causada por larvas da tênia encontrada em peixes, que pode causar problemas neurológicos se as larvas migraram para o cérebro.', 10),
('Malária', 'Doença parasitária transmitida por mosquitos Anopheles, causando febre, calafrios e anemia. Pode ser fatal se não tratada.', 20),
('Doença de Chagas', 'Infecção causada pelo parasita Trypanosoma cruzi, transmitido por percevejos. Pode causar problemas cardíacos e digestivos graves.', 10),
('Dengue', 'Doença viral transmitida por mosquitos Aedes, causando febre alta, dor muscular e nas articulações. Em casos graves, pode levar a hemorragias.', 2),
('Arbovirose', 'Infecção viral transmitida por picadas de insetos que se alimentam de plantas infectadas, como o vírus da febre do Nilo Ocidental.', 5),
('Intoxicação por plantas', 'Envenenamento causado pela ingestão de plantas tóxicas, levando a sintomas variados como náuseas, vômitos e até a morte.', 10);


INSERT INTO especie_doencas (especie_id, doenca_id, afeta_humanos) VALUES
(1, 1, 1),
(2, 1, 1),
(3, 2, 1),
(4, 2, 1),
(5, 9, 0),
(6, 8, 0),
(7, 10, 1),
(8, 9, 1),
(9, 2, 1),
(10, 1, 1),
(11, 1, 1),
(12, 1, 1),
(13, 1, 1),
(14, 5, 0),
(15, 5, 0),
(16, 7, 1),
(17, 7, 1),
(18, 10, 0),
(19, 10, 0),
(20, 10, 0),
(21, 5, 1),
(22, 5, 1),
(23, 5, 1),
(24, 5, 1),
(25, 16, 0),
(26, 16, 0),
(27, 16, 0),
(28, 16, 0),
(29, 16, 0),
(30, 16, 0),
(31, 16, 0),
(32, 16, 0),
(33, 18, 0),
(34, 18, 0),
(35, 18, 0),
(36, 18, 0),
(37, 18, 0),
(38, 18, 0),
(39, 1, 0),
(40, 1, 0),
(41, 1, 0),
(42, 1, 0),
(43, 1, 0),
(44, 1, 0),
(45, 1, 1),
(46, 1, 1),
(47, 10, 1),
(48, 10, 1),
(49, 10, 0),
(50, 10, 0),
(51, 5, 0),
(52, 5, 0),
(53, 5, 0),
(54, 10, 0),
(55, 10, 0),
(56, 5, 0),
(57, 5, 0),
(58, 5, 0),
(59, 5, 0),
(60, 5, 1),
(61, 5, 1),
(62, 16, 0),
(63, 16, 0),
(64, 16, 0),
(65, 5, 0),
(66, 5, 0),
(67, 16, 0),
(68, 16, 0),
(69, 16, 0),
(70, 16, 0),
(71, 16, 0),
(72, 16, 0),
(73, 16, 0),
(74, 16, 0),
(75, 16, 0),
(76, 16, 0),
(77, 16, 0),
(78, 16, 0),
(79, 16, 0),
(80, 16, 0),
(81, 16, 0),
(82, 16, 0),
(83, 16, 0),
(84, 16, 0);

INSERT INTO tipos_interacoes (tipo) VALUES 
('Predação'),
('Parasitismo'),
('Mutualismo'),
('Comensalismo'),
('Competição'),
('Amensalismo'),
('Neutralismo'),
('Simbiose'),
('Cooperação'),
('Antagonismo');

INSERT INTO interacoes (especie1_id, especie2_id, tipo_interacao_id, descricao) VALUES 
(1, 5, 1, 'Tigre e Basilisco, relação de predador e presa respectivamente, à menos que o tigre olhe nos olhos.'),
(2, 3, 2, 'Águia e  , .'),
(3, 4, 3, 'Rosa Selvagem e  .'),
(4, 8, 4, 'Cogumelos  .'),
(5, 6, 5, 'Leão  '),
(6, 7, 6, 'Coruja das torres e  '),
(7, 8, 7, 'Rosa Brava e'),
(8, 9, 8, 'Cogumelos do campo .'),
(9, 10, 9, 'Onça '),
(10, 1, 10, 'Basilisco .');

INSERT INTO habitats (descricao) VALUES 
('Selva Densa'),
('Montanhas Altas'),
('Campos Mágicos'),
('Florestas Encantadas'),
('Deserto Árido'),
('Pântano Místico'),
('Rios da Selva'),
('Planícies Verdes'),
('Túneis Subterrâneos'),
('Ruínas Antigas');

INSERT INTO especie_habitats (especie_id, habitat_id) VALUES 
(1, 1),
(2, 1),
(3, 4),
(4, 3),
(5, 1),
(6, 2),
(7, 4),
(8, 3),
(9, 5),
(10, 9);

INSERT INTO localizacao (coordenadas, descricao, altitude, area_protegida, area_desmatada) VALUES 
(ST_SetSRID(ST_MakePoint(-70.0, 40.0), 4326), 'Selva Densa', 200, TRUE, FALSE),
(ST_SetSRID(ST_MakePoint(-80.0, 45.0), 4326), 'Montanhas Altas', 1500, TRUE, TRUE),
(ST_SetSRID(ST_MakePoint(-75.0, 30.0), 4326), 'Campos Mágicos', 300, TRUE, FALSE),
(ST_SetSRID(ST_MakePoint(-65.0, 35.0), 4326), 'Florestas', 500, TRUE, FALSE),
(ST_SetSRID(ST_MakePoint(-60.0, 25.0), 4326), 'Deserto', 600, FALSE, TRUE),
(ST_SetSRID(ST_MakePoint(-55.0, 50.0), 4326), 'Pântano Místico', 150, FALSE, TRUE),
(ST_SetSRID(ST_MakePoint(-70.0, 20.0), 4326), 'Rios da Selva', 100, TRUE, FALSE),
(ST_SetSRID(ST_MakePoint(-75.0, 40.0), 4326), 'Planícies Verdes', 200, TRUE, FALSE),
(ST_SetSRID(ST_MakePoint(-80.0, 35.0), 4326), 'Túneis Subterrâneos', 50, FALSE, TRUE),
(ST_SetSRID(ST_MakePoint(-85.0, 45.0), 4326), 'Ruínas Antigas', 300, TRUE, FALSE);

INSERT INTO observacoes (especie_id, localizacao_id, data_hora, observador, notas) VALUES 
(1, 1, '2024-07-30 08:00:00', 'Shiryu', '.'),
(2, 2, '2024-07-30 09:00:00', 'Griffith', '.'),
(3, 3, '2024-07-30 10:00:00', 'Afrodite de Peixes', '.'),
(4, 4, '2024-07-30 11:00:00', 'Radagast, o Marrom', '.'),
(5, 5, '2024-07-30 12:00:00', 'Aioria', 'o.'),
(6, 6, '2024-07-30 13:00:00', 'Saori Kido', '.'),
(7, 7, '2024-07-30 14:00:00', 'Ash Ketchum da cidade de Pallet', '.'),
(8, 8, '2024-07-30 15:00:00', 'Afrodite de Peixes', '.'),
(9, 9, '2024-07-30 16:00:00', 'Radagast, o Marrom', '.'),
(10, 10, '2024-07-30 17:00:00', 'Tom Riddle', 'Basiliscos patrulhando ruínas antigas sob Hogwarts.');
